### ISSUE TITLE
2017-09-24-CSS三栏布局学习笔记

### ISSUE THREAD

**Issue by lampui** [lampui/myblog#6]
今天学习了两边定宽，中间自适应的三栏布局，有 4 种实现方法，接下来一一记录。

## 绝对定位

```html
<div class="container">
    <div class="left"></div>
    <div class="main"></div>
    <div class="right"></div>
</div>
```

```css
.container {
    position: relative;
    height: 100vh;
    margin: 0;
    padding: 0;
}
.left, .right {
    position: absolute;
    top: 0;
    background: silver;
    height: 100%;
}
.left {
    left: 0;
    width: 200px;
}
.right {
    right: 0;
    width: 300px;
}
.main {
    margin: 0 300px 0 200px;
    height: 100vh;
    background: blue;
}
```
## 圣杯布局

```html
<div class="container">
    <div class="main column"></div>
    <div class="left column"></div>    
    <div class="right column"></div>
</div>
```

```css
.container {
    padding: 0 300px 0 200px;
}
.container .column{
    height: 100vh;
    float: left;
    position: relative;
}
.left {
    width: 200px;
    margin-left: -100%;
    left: -200px;
    background: red;
}
.main {
    width: 100%;
    background: blue;
}
.right {
    width: 300px;
    margin-right: -300px;
    /*
    上面这句也可以写成：
    margin-left: -300px;
    right: -300px;
    */
    background: red;
}
```

## 双飞翼布局

```html
<div class="container">
    <div class="main column"></div>
    <div class="left column"></div>    
    <div class="right column"></div>
</div>
```

```css
.container {
  height: 100vh;
}
.container > div {
  height: 100vh;
  float: left;
}
.left {
  width: 200px;
  margin-left: -100%;
  background: blue;
}
.right {
  width: 300px;
  margin-left: -300px;
  background: green;
}
.main {
  width: 100%;
  background: brown;
}
.inner {
  margin: 0 300px 0 200px;
}
```
## 流动布局实现
```html
<div class="container">
    <div class="left"></div>
    <div class="right"></div>
    <div class="main"></div>
</div>
```
```css
.container {
    height: 100vh;
}
.container > div{
    height: 100vh;
}
.left {
    float: left;
    width: 200px;
    background: red;
}
.main {
    margin: 0 300px 0 200px;
    background: blue;
}
.right {
    float: right;
    width: 300px;
    background: yellow;
}

```
